using MessManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace MessManagementSystem.Controllers
{
    public class PaymentController : Controller
    {
        private readonly MessDbContext _context;

        public PaymentController(MessDbContext context)
        {
            _context = context;
        }

        // 1. Show the "Fake" JazzCash Payment Screen
        [HttpGet]
        public IActionResult JazzCashGateway(int billId)
        {
            var bill = _context.Bills.Find(billId);
            if (bill == null || bill.IsPaid == true)
            {
                return RedirectToAction("Dashboard", "Teacher");
            }

            return View(bill);
        }

        // 2. Process the Payment (When user clicks "Confirm Payment")
        [HttpPost]
        [HttpPost]
        public IActionResult ProcessPayment(int billId, string stripeToken)
        {
            var bill = _context.Bills.Find(billId);
            if (bill == null) return RedirectToAction("Dashboard", "Teacher");

            try
            {
                // 1. Create the Charge on Stripe
                var options = new Stripe.ChargeCreateOptions
                {
                    Amount = (long)(bill.TotalAmount * 100), // Stripe expects amount in Cents (Rs 100 = 10000 cents)
                    Currency = "pkr",
                    Description = $"Mess Bill Payment - {bill.BillMonth}/{bill.BillYear}",
                    Source = stripeToken, // The token generated by the frontend
                };

                var service = new Stripe.ChargeService();
                Charge charge = service.Create(options);

                // 2. If Stripe says "succeeded", save to our Database
                if (charge.Status == "succeeded")
                {
                    var user = _context.Users.Find(bill.UserId);

                    var payment = new Payment
                    {
                        UserId = user.UserId,
                        BillId = bill.BillId,
                        AmountPaid = bill.TotalAmount,
                        TransactionToken = charge.Id, // Real Stripe Transaction ID
                        PaymentDate = DateTime.Now
                    };
                    _context.Payments.Add(payment);

                    bill.IsPaid = true;
                    user.CurrentBalance = (user.CurrentBalance ?? 0) - bill.TotalAmount;

                    _context.SaveChanges();

                    return View("PaymentSuccess", payment);
                }
            }
            catch (StripeException e)
            {
                ViewBag.Error = e.Message;
                return View("JazzCashGateway", bill);
            }

            return RedirectToAction("Dashboard", "Teacher");
        }
    }
}